- Add missing constant values of CSP according to https://developer.m…
apache/wicket pull request #761
Opened 2024-01-07 16:09 UTC by renoth

…ozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#scheme-source

2024-01-07 16:10 UTC, renoth commented
See also https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#scheme-source

2024-01-08 06:51 UTC, martin-g requested changes
The change looks good but:
1) we will need a JIRA ticket for the changelog
2) it would be good to add some new unit tests

2024-01-08 08:28 UTC, renoth commented
Ticket is https://issues.apache.org/jira/browse/WICKET-7094

2024-01-08 08:42 UTC, martin-g approved these changes

2024-01-08 08:54 UTC, merged

2024-01-08 08:58 UTC, martin-g commented
Thank you for the contribution, @renoth !